build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false
  excludes: ''

processors:
  active: true
  exclude: ['DetektProgressListener']

console-reports:
  active: true
  exclude: ['ProjectStatisticsReport','ComplexityReport','NotificationReport','FindingsReport','FileBasedFindingsReport']

output-reports:
  active: true

comments:
  active: true
  AbsentOrWrongFileLicense: {active: false}
  CommentOverPrivateFunction: {active: false}
  CommentOverPrivateProperty: {active: false}
  DeprecatedBlockTag: {active: false}
  EndOfSentenceFormat: {active: false}
  KDocReferencesNonPublicProperty: {active: false}
  OutdatedDocumentation: {active: false}
  UndocumentedPublicClass: {active: false}
  UndocumentedPublicFunction: {active: false}
  UndocumentedPublicProperty: {active: false}

complexity:
  active: true
  ComplexCondition: {active: true, threshold: 4}
  CyclomaticComplexMethod: {active: true, threshold: 15}
  LargeClass: {active: true, threshold: 600}
  LongMethod: {active: true, threshold: 60}
  LongParameterList: {active: true, functionThreshold: 8, constructorThreshold: 10}
  NestedBlockDepth: {active: true, threshold: 4}
  TooManyFunctions: {active: true, thresholdInFiles: 11, thresholdInClasses: 11}

coroutines:
  active: true
  InjectDispatcher: {active: true, dispatcherNames: ['IO','Default','Unconfined']}
  RedundantSuspendModifier: {active: true}
  SleepInsteadOfDelay: {active: true}
  SuspendFunWithFlowReturnType: {active: true}

empty-blocks:
  active: true
  EmptyCatchBlock: {active: true}
  EmptyClassBlock: {active: true}
  EmptyFunctionBlock: {active: true}
  EmptyIfBlock: {active: true}
  EmptyTryBlock: {active: true}

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation: {active: true}
  PrintStackTrace: {active: true}
  RethrowCaughtException: {active: true}
  ReturnFromFinally: {active: true}
  SwallowedException: {active: true}
  ThrowingExceptionFromFinally: {active: true}
  ThrowingExceptionsWithoutMessageOrCause: {active: true}
  TooGenericExceptionCaught: {active: true}
  TooGenericExceptionThrown: {active: true}

naming:
  active: true
  ClassNaming: {active: true, classPattern: '[A-Z][a-zA-Z0-9]*'}
  FunctionNaming: {active: true, functionPattern: '[a-z][a-zA-Z0-9]*'}
  ConstructorParameterNaming: {active: true}
  EnumNaming: {active: true}
  VariableNaming: {active: true}
  TopLevelPropertyNaming: {active: true}
  ObjectPropertyNaming: {active: true}
  PackageNaming: {active: true}

performance:
  active: true
  ArrayPrimitive: {active: true}
  ForEachOnRange: {active: true}
  UnnecessaryTemporaryInstantiation: {active: true}

potential-bugs:
  active: true
  AvoidReferentialEquality: {active: true}
  DoubleMutabilityForCollection: {active: true}
  EqualsAlwaysReturnsTrueOrFalse: {active: true}
  EqualsWithHashCodeExist: {active: true}
  ExplicitGarbageCollectionCall: {active: true}
  HasPlatformType: {active: true}
  IgnoredReturnValue: {active: true}
  ImplicitDefaultLocale: {active: true}
  InvalidRange: {active: true}
  MapGetWithNotNullAssertionOperator: {active: true}
  UnnecessaryNotNullOperator: {active: true}
  UnnecessarySafeCall: {active: true}
  UnsafeCallOnNullableType: {active: true}
  UnsafeCast: {active: true}

style:
  active: true
  ForbiddenComment: {active: true}
  ForbiddenVoid: {active: true}
  FunctionOnlyReturningConstant: {active: true}
  LoopWithTooManyJumpStatements: {active: true}
  MagicNumber: {active: true}
  MaxLineLength: {active: true, maxLineLength: 120}
  NestedClassesVisibility: {active: true}
  NewLineAtEndOfFile: {active: true}
  ObjectLiteralToLambda: {active: true}
  OptionalAbstractKeyword: {active: true}
  ProtectedMemberInFinalClass: {active: true}
  RedundantHigherOrderMapUsage: {active: true}
  ReturnCount: {active: true, max: 4}
  SafeCast: {active: true}
  SerialVersionUIDInSerializableClass: {active: true}
  UnnecessaryAbstractClass: {active: true}
  UnnecessaryApply: {active: true}
  UnnecessaryFilter: {active: true}
  UnnecessaryInheritance: {active: true}
  UnusedPrivateClass: {active: true}
  UnusedPrivateMember: {active: true}
  UseAnyOrNoneInsteadOfFind: {active: true}
  UseArrayLiteralsInAnnotations: {active: true}
  UseCheckNotNull: {active: true}
  UseCheckOrError: {active: true}
  UseRequire: {active: true}
  UseRequireNotNull: {active: true}
  UselessCallOnNotNull: {active: true}
  VarCouldBeVal: {active: true}
  WildcardImport: {active: true}
