app:
  queue:
    financial-transaction-processed:
      name: "transacoes-financeiras-processadas"
      enabled: true
      dlq:
        name: "transacoes-financeiras-processadas-dlq"
        reprocess: false
