springdoc:
  api-docs:
    enabled: "${enable.swagger:true}"
    packagesToScan: ""
  swagger-ui:
    enabled: "${springdoc.api-docs.enabled}"
    path: /docs
    url: /api-docs.yaml
    disable-swagger-default-url: true