resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: TIME_BASED
      slidingWindowSize: 100
      minimumNumberOfCalls: 100
      waitDurationInOpenState: 60000
      failureRateThreshold: 50
  instances:
    resource-jpa-cb:
      baseConfig: default
    jms-listener-account-balance-cb:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      failAfterMaxAttempts: false
