wiremock:
  server:
    port: 0

spring:
  cloud:
    aws:
      region:
        static: sa-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4645
        listener:
          max-number-of-messages: 10
          deletion-policy: ON_SUCCESS
          auto-startup: true
  datasource:
    url: jdbc:postgresql://localhost:25440/postgres
    username: postgres
    password: postgres

logging:
  level:
    io.awspring.cloud.sqs: DEBUG
    software.amazon.awssdk: INFO

app:
  queue:
    financial-transaction-processed:
      name: "transacoes-financeiras-processadas"
      dlq:
        name: "transacoes-financeiras-processadas-dlq"
