{
 "title": "Account Balance Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Database Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(insertOrUpdate_account_affected_rows_count_total[1m])",
     "legendFormat": "Inserts succesfully"
    },
    {
     "expr": "increase(insertOrUpdate_account_failure_count_total[1m])",
     "legendFormat": "Inserts failed"
    }
   ]
  },
  {
   "title": "SQS Financial Transaction Listener",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(financial_transaction_messages_success_total[1m])",
     "legendFormat": "Message processed successfully"
    },
    {
     "expr": "increase(financial_transaction_messages_failure_total[1m])",
     "legendFormat": "Message processed failure"
    }
   ]
  },
  {
   "title": "Financial Transaction Process By Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(financial_transaction_batch_processing_time_seconds_count[1m]) * 60",
     "legendFormat": "Batchs by seconds"
    }
   ]
  }
 ]
}